import {
  Box,
  Button,
  Center,
  Flex,
  Heading,
  useColorMode,
} from "@chakra-ui/react";
import Head from "next/head";
import FormikForms from "./components/FormikForms";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div>
      <Head>
        <title>Working with forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Flex justify="space-between" p={12} textAlign="center">
          <Heading textTransform="uppercase">
            Working with forms using formik
          </Heading>
          <Button onClick={toggleColorMode} textTransform="uppercase">
            Toggle {colorMode === "light" ? "Dark" : "Light"}
          </Button>
        </Flex>

        <div>
          <FormikForms />
        </div>
      </div>
    </div>
  );
}
